server:
  port: 8081

spring.jpa:
  database: POSTGRESQL
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/helpfull_service
  username: postgres
  password: ${DB_PASSWORD}

flyway:
  enabled: true
  baseline-on-migrate: true
  validate-on-migrate: true
  locations: classpath:db/migration