server:
  port: 8081

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:helpfull_service;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

jwt:
  secret: ${JWT_SECRET}
  lifetime: 36000000


#spring.datasource:
#  driverClassName: org.postgresql.Driver
#  url: jdbc:postgresql://localhost:5432/helpfull_service
#  username: postgres
#  password: ${DB_PASSWORD}
#
#flyway:
#  enabled: true
#  baseline-on-migrate: true
#  validate-on-migrate: true
#  locations: classpath:db/migration

